sudo: required
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - sudo apt-get install expect
  - ./login.sh $METEOR_USERNAME $METEOR_PASSWORD
 
cache:
  directories:
    - node_modules
 
before_script:
  - meteor npm install

after_success:
  - DEPLOY_HOSTNAME=us-east-1.galaxy-deploy.meteor.com meteor deploy job-search.meteorapp.com
  - echo "Deployment successful"