sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
cache:
  directories:
    - node_modules
 
before_script:
  - meteor npm install
 
script:
  - meteor add react-meteor-data
  - meteor add accounts-ui accounts-password
  - meteor add dispatch:mocha-phantomjs
  - meteor test --once --driver-package dispatch:mocha-phantomjs
  - meteor build $HOME/build.tgz

deploy:
  - provider: script
  - script: DEPLOY_HOSTNAME=us-east-1.galaxy-deploy.meteor.com meteor deploy --settings settings.json job-search.meteorapp.com
  - on:
    - branch: master